# Generated by Django 5.2.7 on 2025-10-28 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='full_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
