# Generated by Django 5.2.7 on 2025-10-28 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings_app', '0002_participant_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='email',
            field=models.EmailField(help_text='Die E-Mail-Adresse muss eindeutig sein.', max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='first_name',
            field=models.CharField(help_text='Geben Sie den Vornamen des Teilnehmers ein.', max_length=100),
        ),
        migrations.AlterField(
            model_name='participant',
            name='last_name',
            field=models.CharField(help_text='Geben Sie den Nachnamen des Teilnehmers ein.', max_length=100),
        ),
    ]
